// <auto-generated />
namespace EatAsYouGoApi.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingRefreshToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingRefreshToken));
        
        string IMigrationMetadata.Id
        {
            get { return "201809301806411_AddingRefreshToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
